const key='theLogbookV1';
let db=JSON.parse(localStorage.getItem(key)||'{"trips":[],"lures":[],"patterns":[]}');
const $=id=>document.getElementById(id), value=id=>$(id).value.trim(), number=id=>Number(value(id)||0);
$('date').valueAsDate=new Date();

function save(){localStorage.setItem(key,JSON.stringify(db));render()}
function go(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('on',b.dataset.go===id));render()}
document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.go)));

function addFish(){let box=document.createElement('div');box.className='fishbox';box.innerHTML='<div class="row"><div><label>Fish weight</label><input class="fWeight" placeholder="2.5"></div><div><label>Length</label><input class="fLength" placeholder="17 in"></div></div><label>Name / Notes</label><input class="fNote" placeholder="Dumbass Dave, bank bite, crushed it..."><button class="danger" onclick="this.parentElement.remove()">Remove Fish</button>';$('fishEntries').appendChild(box)}
window.addFish=addFish;$('addFishBtn').addEventListener('click',addFish);
function fishData(){return [...document.querySelectorAll('.fishbox')].map(b=>({weight:b.querySelector('.fWeight').value.trim(),length:b.querySelector('.fLength').value.trim(),note:b.querySelector('.fNote').value.trim()}))}

$('saveTrip').addEventListener('click',()=>{db.trips.unshift({id:Date.now(),date:value('date'),lake:value('lake'),spot:value('spot'),waterTemp:value('waterTemp'),airTemp:value('airTemp'),clarity:value('clarity'),sky:value('sky'),cover:value('cover'),grass:value('grass'),lure:value('lure'),weight:value('weight'),color:value('color'),trailer:value('trailer'),blade:value('blade'),rod:value('rod'),line:value('line'),bites:number('bites'),landed:number('landed'),lost:number('lost'),biggest:value('biggest'),fish:fishData(),confidence:number('confidence'),grassScore:number('grassScore'),hookups:number('hookups'),hunting:number('hunting'),fishAgain:$('fishAgain').checked,lesson:value('lesson'),notes:value('notes')});save();alert('Trip saved.');go('history')});
$('saveLure').addEventListener('click',()=>{if(!value('vName')){alert('Name the lure first.');return}db.lures.unshift({id:Date.now(),name:value('vName'),status:value('vStatus'),notes:value('vNotes')});$('vName').value='';$('vNotes').value='';save()});
$('savePattern').addEventListener('click',()=>{db.patterns.unshift({id:Date.now(),lake:value('pLake'),spot:value('pSpot'),best:value('pBest'),backup:value('pBackup'),why:value('pWhy')});save()});
$('clearBtn').addEventListener('click',()=>{if(confirm('Delete all Logbook data?')){db={trips:[],lures:[],patterns:[]};save()}});
$('exportBtn').addEventListener('click',()=>{let blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'});let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='the-logbook-backup.json';a.click()});
$('importBtn').addEventListener('click',()=>{try{db=JSON.parse(value('importText'));save();alert('Backup imported.')}catch(e){alert('That backup did not import.')}});
$('search').addEventListener('input',render);

function group(arr,prop){return arr.reduce((o,x)=>{let k=x[prop]||'Unknown';(o[k]=o[k]||[]).push(x);return o},{})}
function sum(arr,prop){return arr.reduce((a,x)=>a+Number(x[prop]||0),0)}
function avg(arr,prop){let v=arr.map(x=>Number(x[prop]||0)).filter(Boolean);return v.length?(v.reduce((a,b)=>a+b,0)/v.length).toFixed(1):'—'}
function allFish(){let out=[];db.trips.forEach(t=>(t.fish||[]).forEach(f=>out.push({...f,lure:t.lure,lake:t.lake,date:t.date})));return out}
function delTrip(id){db.trips=db.trips.filter(t=>t.id!==id);save()} window.delTrip=delTrip;

function render(){let t=db.trips,b=sum(t,'bites'),l=sum(t,'landed'),lost=sum(t,'lost');$('dashboard').innerHTML=`<div class="stat"><span>Trips</span><b>${t.length}</b></div><div class="stat"><span>Bites</span><b>${b}</b></div><div class="stat"><span>Landed</span><b>${l}</b></div><div class="stat"><span>Lost</span><b>${lost}</b></div><div class="stat"><span>Landing %</span><b>${b?Math.round(l/b*100):0}%</b></div>`;$('chief').innerHTML=chiefReport();renderHistory();renderPerformance();renderVault();renderPatterns();renderTrophy()}
function chiefReport(){if(!db.trips.length)return 'Save your first trip and Chief will start finding patterns.';let by=group(db.trips,'lure'),best=Object.entries(by).sort((a,b)=>sum(b[1],'bites')-sum(a[1],'bites'))[0],last=db.trips[0];return `Best lure by bites: <b class="gold">${best?best[0]:'—'}</b><br>Last trip: <b>${last.lake||'Unknown'}</b> · ${last.lure||'No lure'} · ${last.bites} bites.<br>${last.lesson?'<span class="pill">'+last.lesson+'</span>':'Add lessons to sharpen Chief.'}`}
function renderHistory(){let q=$('search').value.toLowerCase();let trips=db.trips.filter(t=>JSON.stringify(t).toLowerCase().includes(q));$('historyList').innerHTML=trips.length?trips.map(t=>`<div class="card"><b>${t.date||''} — ${t.lake||'Unknown'}</b><br><span class="small">${t.spot||''}</span><p><span class="pill">${t.lure||'Lure'}</span><span class="pill">${t.bites} bites</span><span class="pill">${t.landed} landed</span><span class="pill">${t.lost} lost</span><span class="pill">Conf ${t.confidence||'—'}</span></p><p>${t.lesson||t.notes||''}</p><button class="danger" onclick="delTrip(${t.id})">Delete</button></div>`).join(''):'<p class="small">No trips saved yet.</p>'}
function renderPerformance(){let by=group(db.trips,'lure');$('performanceList').innerHTML=Object.entries(by).length?Object.entries(by).map(([name,arr])=>{let b=sum(arr,'bites'),l=sum(arr,'landed'),rate=b?Math.round(l/b*100):0;return `<div class="card"><h3>${name}</h3><div class="stat"><span>Trips</span><b>${arr.length}</b></div><div class="stat"><span>Bites</span><b>${b}</b></div><div class="stat"><span>Landed</span><b>${l}</b></div><div class="stat"><span>Landing %</span><b>${rate}%</b></div><div class="stat"><span>Confidence</span><b>${avg(arr,'confidence')}</b></div><div class="stat"><span>Grass Clearance</span><b>${avg(arr,'grassScore')}</b></div><div class="stat"><span>Hookups</span><b>${avg(arr,'hookups')}</b></div><div class="stat"><span>Action / Hunt</span><b>${avg(arr,'hunting')}</b></div></div>`}).join(''):'<p class="small">No performance data yet.</p>'}
function renderVault(){$('vaultList').innerHTML=db.lures.length?db.lures.map(l=>`<div class="card"><b>${l.name}</b> <span class="pill">${l.status}</span><p>${l.notes||''}</p></div>`).join(''):'<p class="small">No lures saved yet.</p>'}
function renderPatterns(){$('patternList').innerHTML=db.patterns.length?db.patterns.map(p=>`<div class="card spot"><b>${p.lake||'Lake'} — ${p.spot||'Spot'}</b><p><span class="pill">Best: ${p.best||'—'}</span><span class="pill">Backup: ${p.backup||'—'}</span></p><p>${p.why||''}</p></div>`).join(''):'<p class="small">No pattern spots yet.</p>'}
function renderTrophy(){let fish=allFish().sort((a,b)=>Number(b.weight||0)-Number(a.weight||0));$('trophyList').innerHTML=fish.length?fish.map(f=>`<div class="card"><b>${f.weight||'?'} lb</b> <span class="pill">${f.lure}</span><br><span class="small">${f.date} · ${f.lake}</span><p>${f.note||''}</p></div>`).join(''):'<p class="small">Add fish entries inside a trip to build the Trophy Room.</p>'}
render();
